### ISSUE TITLE
could not find implicit value for evidence parameter of type edu.berkeley.cs.amplab.spark.indexedrdd.KeySerializer[Int]

### ISSUE THREAD

**Issue by pecanNBU** [amplab/spark-indexedrdd#31]
could not find implicit value for evidence parameter of type edu.berkeley.cs.amplab.spark.indexedrdd.KeySerializer[Int]

**Comment by pecanNBU** [comment]
i have solved this problem, this is caused by scala version conflict. in my project use scala 2.11.8, so i changed use IndexedRDD 0.4.0

**Comment by TianZonglin** [comment]
Hi, I've got a same error when I use IndexedRDD, but after I changed the version to 0.4.0, it didn't work.
I want to know more about your solutions. Thanks~

**Comment by pecanNBU** [comment]
what's you scala version?

**Comment by TianZonglin** [comment]
2.11.8
Thanks, I've solved this problem with adding `import edu.berkeley.cs.amplab.spark.indexedrdd.IndexedRDD._`, and I find that's caused by the IDEA's automatic codecheck, it deleted the `IndexedRDD._` automatically. 
So, I means that both `IndexedRDD` and `IndexedRDD._`  are necessary.
Btw, your solution is necessary too, it really needs to work with the version 0.4.0.

**Comment by pecanNBU** [comment]
yeh, you are right
